In [2]:
import pandas as pd
import json
import os
import mysql.connector
from sqlalchemy import create_engine

In [7]:
def Agg_transaction_details():
    path="D:/PHONEPAY/Data/pulse/data/aggregated/transaction/country/india/state/"
    Agg_state_list=os.listdir(path)
    Agg_state_list
    clm={'State':[], 'Year':[],'Quater':[],'Transaction_type':[], 'Transaction_count':[], 'Transaction_amount':[]}

    for i in Agg_state_list:
        p_i=path+i+"/"
        Agg_yr=os.listdir(p_i)
        for j in Agg_yr:
            p_j=p_i+j+"/"
            Agg_yr_list=os.listdir(p_j)
            for k in Agg_yr_list:
                p_k=p_j+k
                Data=open(p_k,'r')
                D=json.load(Data)
                for z in D['data']['transactionData']:
                    Name=z['name']
                    count=z['paymentInstruments'][0]['count']
                    amount=z['paymentInstruments'][0]['amount']
                    clm['Transaction_type'].append(Name)
                    clm['Transaction_count'].append(count)
                    clm['Transaction_amount'].append(amount)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
    #Succesfully created a dataframe
    Agg_Trans=pd.DataFrame(clm)
    return Agg_Trans

In [5]:
def Agg_user_details():
    path="D:/PHONEPAY/Data/pulse/data/aggregated/user/country/india/state/"
    Agg_state_list=os.listdir(path)
    Agg_state_list
    clm={'State':[], 'Year':[],'Quater':[],'Registered_Users':[], 'Brand_Usage':[], 'Brand_Count':[],'Brand_Percentage':[],'Appopens':[]}

    for i in Agg_state_list:
        p_i=path+i+"/"
        Agg_yr=os.listdir(p_i)
        for j in Agg_yr:
            p_j=p_i+j+"/"
            Agg_yr_list=os.listdir(p_j)
            for k in Agg_yr_list:
                p_k=p_j+k
                Data=open(p_k,'r')
                D=json.load(Data)
                reguser=D['data']['aggregated']['registeredUsers']
                appopen=D['data']['aggregated']['appOpens']
                if D['data']['usersByDevice']==None:
                    clm['Brand_Usage'].append("Not_provided")
                    clm['Brand_Count'].append("Not_Provided")
                    clm['Brand_Percentage'].append("Not_Provided")
                    clm['Appopens'].append(appopen)
                    clm['Registered_Users'].append(reguser)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
                else:
                    for z in D['data']['usersByDevice']:
                        bname=z['brand']
                        bcount=z['count']
                        bpercent=z['percentage']
                        clm['Appopens'].append(appopen)
                        clm['Brand_Usage'].append(bname)
                        clm['Brand_Count'].append(bcount)
                        clm['Brand_Percentage'].append(bpercent)
                        clm['Registered_Users'].append(reguser)
                        clm['State'].append(i)
                        clm['Year'].append(j)
                        clm['Quater'].append(int(k.strip('.json')))
    #Succesfully created a dataframe
    Agg_User=pd.DataFrame(clm)
    return Agg_User

In [9]:
def Map_transaction_details():
    path="D:/PHONEPAY/Data/pulse/data/map/transaction/hover/country/india/state/"
    Agg_state_list=os.listdir(path)
    Agg_state_list
    clm={'District':[],'State':[], 'Year':[],'Quater':[], 'Transaction_count':[], 'Transaction_amount':[]}

    for i in Agg_state_list:
        p_i=path+i+"/"
        Agg_yr=os.listdir(p_i)
        for j in Agg_yr:
            p_j=p_i+j+"/"
            Agg_yr_list=os.listdir(p_j)
            for k in Agg_yr_list:
                p_k=p_j+k
                Data=open(p_k,'r')
                D=json.load(Data)
                for z in D['data']['hoverDataList']:
                    District=z['name']
                    count=z['metric'][0]['count']
                    amount=z['metric'][0]['amount']
                    clm['District'].append(District)
                    clm['Transaction_count'].append(count)
                    clm['Transaction_amount'].append(amount)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
    #Succesfully created a dataframe
    Map_Trans=pd.DataFrame(clm)
    return Map_Trans

In [10]:
def Map_User_details():
    path="D:/PHONEPAY/Data/pulse/data/map/user/hover/country/india/state/"
    Agg_state_list=os.listdir(path)
    Agg_state_list
    clm={'District':[],'State':[], 'Year':[],'Quater':[], 'Registered_Users':[]}

    for i in Agg_state_list:
        p_i=path+i+"/"
        Agg_yr=os.listdir(p_i)
        for j in Agg_yr:
            p_j=p_i+j+"/"
            Agg_yr_list=os.listdir(p_j)
            for k in Agg_yr_list:
                p_k=p_j+k
                Data=open(p_k,'r')
                D=json.load(Data)
                for z in D['data']['hoverData']:
                    District=z
                    count=D['data']['hoverData'][z]['registeredUsers']
                    clm['District'].append(District)
                    clm['Registered_Users'].append(count)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
    #Succesfully created a dataframe
    Map_User=pd.DataFrame(clm)
    return Map_User

In [59]:
def Top_trans_details():
    path="D:/PHONEPAY/Data/pulse/data/top/transaction/country/india/state/"
    Agg_state_list=os.listdir(path)

    clm={'Pincode':[],'District':[],'State':[], 'Year':[],'Quater':[], 'District_count':[],'District_amount':[]}

    for i in Agg_state_list:
        p_i=path+i+"/"
        Agg_yr=os.listdir(p_i)
        for j in Agg_yr:
            p_j=p_i+j+"/"
            Agg_yr_list=os.listdir(p_j)
            for k in Agg_yr_list:
                p_k=p_j+k
                Data=open(p_k,'r')
                D=json.load(Data)
                for z in range (len(D['data']['districts'])):
                    pinc=D['data']['pincodes'][z]['entityName']
                    District=D['data']['districts'][z]['entityName']
                    dcount=D['data']['districts'][z]['metric']['count']
                    damount=D['data']['districts'][z]['metric']['amount']
                    clm['Pincode'].append(pinc)
                    clm['District'].append(District)
                    clm['District_count'].append(dcount)
                    clm['District_amount'].append(damount)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
    #Succesfully created a dataframe
    Top_trans=pd.DataFrame(clm)
    return Top_trans

In [57]:
def top_user_details():
    path="D:/PHONEPAY/Data/pulse/data/top/user/country/india/state/"
    Agg_state_list=os.listdir(path)

    clm={'Pincode':[],'District':[],'State':[], 'Year':[],'Quater':[], 'Registered_Users':[]}

    for i in Agg_state_list:
        p_i=path+i+"/"
        Agg_yr=os.listdir(p_i)
        for j in Agg_yr:
            p_j=p_i+j+"/"
            Agg_yr_list=os.listdir(p_j)
            for k in Agg_yr_list:
                p_k=p_j+k
                Data=open(p_k,'r')
                D=json.load(Data)
                for z in range (len(D['data']['districts'])):
                    pinc=D['data']['pincodes'][z]['name']
                    District=D['data']['districts'][z]['name']
                    dregisteruser=D['data']['districts'][z]['registeredUsers']
                    clm['District'].append(District)
                    clm['Registered_Users'].append(dregisteruser)
                    clm['Pincode'].append(pinc)
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
    #Succesfully created a dataframe
    Top_user=pd.DataFrame(clm)
    return Top_user

In [13]:
def map_tot_trans_details():
    path="D:/PHONEPAY/Data/pulse/data/map/transaction/hover/country/india/"
    Agg_yr=os.listdir(path)
    Agg_yr
    clm={'State':[], 'Year':[],'Quater':[], 'Transaction_count':[], 'Transaction_amount':[]}

    for j in Agg_yr:
            p_j=path+j+"/"
            Agg_yr_list=os.listdir(p_j)
            if j=='state':
                    break
            for k in Agg_yr_list:
                p_k=p_j+k
                Data=open(p_k,'r')
                D=json.load(Data)
                for z in D['data']['hoverDataList']:
                    name=z['name']
                    count=z['metric'][0]['count']
                    amount=z['metric'][0]['amount']
                    clm['Transaction_count'].append(count)
                    clm['Transaction_amount'].append(amount)
                    clm['State'].append(name)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
    #Succesfully created a dataframe
    Map_Trans=pd.DataFrame(clm)
    return Map_Trans

In [14]:
def Map_tot_User_details():
    path="D:/PHONEPAY/Data/pulse/data/map/user/hover/country/india/"
    Agg_yr=os.listdir(path)
    clm={'State':[], 'Year':[],'Quater':[], 'Registered_Users':[]}

    for j in Agg_yr:
            p_j=path+j+"/"
            Agg_yr_list=os.listdir(p_j)
            if j=='state':
                 break
            for k in Agg_yr_list:
                p_k=p_j+k
                Data=open(p_k,'r')
                D=json.load(Data)
                for z in D['data']['hoverData']:
                    count=D['data']['hoverData'][z]['registeredUsers']
                    clm['Registered_Users'].append(count)
                    clm['State'].append(z)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
    #Succesfully created a dataframe
    Map_User=pd.DataFrame(clm)
    return Map_User

In [6]:
def stateformat(x):
    for i in x:
        a=i
        a=a.title()
        if '-' in a:
            a=i.replace('-',' ')
            a=a.title()
        if 'Islands' in a:
            a=a[:-8]
        if 'District' in a:
            a=a[:-9]
        if a=='Dadra & Nagar Haveli & Daman & Diu':
            a='Dadra and Nagar Haveli and Daman and Diu'
        x.replace(to_replace=i,value=a,inplace=True)
    return x

In [ ]:
import mysql.connector




mydb = mysql.connector.connect(
 host="localhost",
 user="root",
 password="new_password",


)


print(mydb)
mycursor = mydb.cursor(buffered=True)
engine=create_engine('mysql+mysqlconnector://root:new_password@localhost:3306/project2')

In [ ]:
mycursor.execute("USE project2")
mycursor.execute("CREATE Table Aggregate_Transaction_Details(State VARCHAR(255),Year VARCHAR(5),Quater INT(5),Transaction_type VARCHAR(255),Transaction_count BIGINT,Transaction_amount BIGINT)")
mydb.commit()

In [ ]:
mycursor.execute("CREATE Table Aggregate_User_Details(State VARCHAR(255),Year VARCHAR(5),Quater INT,Registered_Users BIGINT,Brand_Usage VARCHAR(255),Brand_Count BIGINT,Brand_Percentage BIGINT,Appopens BIGINT)")
mydb.commit()

In [ ]:
mycursor.execute("CREATE Table Map_Transaction_Details(District VARCHAR(255),State VARCHAR(255),Year VARCHAR(5),Quater INT,Transaction_count BIGINT,Transaction_amount BIGINT)")
mydb.commit()

In [ ]:
mycursor.execute("CREATE Table Map_User_Details(District VARCHAR(255),State VARCHAR(255),Year VARCHAR(5),Quater INT,Registered_UsersBIGINT)")
mydb.commit()

In [ ]:
mycursor.execute("CREATE Table Map_Total_Transaction_Details(State VARCHAR(255),Year VARCHAR(255),Quater INT,Transaction_count BIGINT,Transaction_amount BIGINT)")
mydb.commit()

In [ ]:
mycursor.execute("CREATE Table Map_Total_User_Details(State VARCHAR(255),Year VARCHAR(5),Quater INT,Registered_Users BIGINT)")
mydb.commit()

In [ ]:
mycursor.execute("CREATE Table Top_Transaction_Details(Pincode INT,District VARCHAR(255),State VARCHAR(255),Year VARCHAR(5),Quater INT,District_count BIGINT,District_amount BIGINT)")
mydb.commit()

In [ ]:
mycursor.execute("CREATE Table Top_User_Details(Pincode INT,District VARCHAR(255),State VARCHAR(255),Year VARCHAR(5),Quater INT,Registered_Users BIGINT)")
mydb.commit()

In [31]:
def load_data():
    global Aggregate_Tran_Det,Aggregate_User_Det,Map_Tran_Det,Map_User_Det,Top_Tran_Det,Top_User_Det
    mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="new_password",


    )


    print(mydb)
    mycursor = mydb.cursor(buffered=True)
    #engine=create_engine('mysql+mysqlconnector://root:new_password@localhost:3306/project2')
    

    #engine=create_engine('mysql+mysqlconnector://3Pq3bYuANQHnv9P.root:M2U9mJayT54djDpU@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/project2')

    Aggregate_Tran_Det=Agg_transaction_details()
    stateformat(Aggregate_Tran_Det['State'])
    for index, row in Aggregate_Tran_Det.iterrows():
        mycursor.execute('INSERT INTO Aggregate_Transaction_Details(State,Year,Quater,Transaction_type,Transaction_count,Transaction_amount) VALUES(%s,%s,%s,%s,%s,%s)',(row['State'],row ['Year'],row['Quater'],row['Transaction_type'],row['Transaction_count'],row['Transaction_amount']))
    #Aggregate_Tran_Det.to_sql(name="Aggregate_Transaction_Details",con=engine,index=False,if_exists='append')

    Aggregate_User_Det=Agg_user_details()
    stateformat(Aggregate_User_Det['State'])
    for index, row in Aggregate_User_Det.iterrows():
        mycursor.execute('INSERT INTO Aggregate_User_Details(State,Year,Quater,Registered_Users,Brand_Usage,Brand_Count,Brand_Percentage,Appopens) VALUES(%s,%s,%s,%s,%s,%s,%s,%s)',(row['State'],row ['Year'],row['Quater'],row['Registered_Users'],row['Brand_Usage'],row['Brand_Count'],row['Brand_Percentage'],row['Appopens']))
    #Aggregate_User_Det.to_sql(name="Aggregate_User_Details",con=engine,index=False,if_exists='append')

    Map_Tran_Det=Map_transaction_details()
    stateformat(Map_Tran_Det['State'])
    stateformat(Map_Tran_Det['District'])
    for index, row in Map_Tran_Det.iterrows():
        mycursor.execute('INSERT INTO Map_Transaction_Details(District,State,Year,Quater,Transaction_count,Transaction_amount) VALUES(%s,%s,%s,%s,%s,%s)',(row['District'],row['State'],row ['Year'],row['Quater'],row['Transaction_count'],row['Transaction_amount']))
    #Map_Tran_Det.to_sql(name="Map_Transaction_Details",con=engine,index=False,if_exists='append')

    Map_User_Det=Map_User_details()
    stateformat(Map_Tran_Det['State'])
    stateformat(Map_Tran_Det['District'])
    for index, row in Map_User_Det.iterrows():
        mycursor.execute('INSERT INTO Map_User_Details(District,State,Year,Quater,Registered_Users) VALUES(%s,%s,%s,%s,%s)',(row['District'],row['State'],row ['Year'],row['Quater'],row['Registered_Users']))
    #Map_User_Det.to_sql(name="Map_User_Details",con=engine,index=False,if_exists='append')

    Map_total_trans_Det=map_tot_trans_details()
    stateformat(Map_total_trans_Det['State'])
    for index, row in Map_total_trans_Det.iterrows():
        mycursor.execute('INSERT INTO Map_Total_Transaction_Details(State,Year,Quater,Transaction_count,Transaction_amount) VALUES(%s,%s,%s,%s,%s)',(row['State'],row ['Year'],row['Quater'],row['Transaction_count'],row['Transaction_amount']))
    #Map_total_trans_Det.to_sql(name="Map_Total_Transaction_Details",con=engine,index=False,if_exists='append')

    Map_total_user_Det=Map_tot_User_details()
    stateformat(Map_total_user_Det['State'])
    for index, row in Map_total_user_Det.iterrows():
        mycursor.execute('INSERT INTO Map_Total_User_Details(State,Year,Quater,Registered_Users) VALUES(%s,%s,%s,%s)',(row['State'],row ['Year'],row['Quater'],row['Registered_Users']))
    #Map_total_user_Det.to_sql(name="Map_Total_User_Details",con=engine,index=False,if_exists='append')

    Top_Tran_Det=Top_trans_details()
    stateformat(Top_Tran_Det['State'])
    stateformat(Top_Tran_Det['District'])
    for index, row in Top_Tran_Det.iterrows():
        mycursor.execute('INSERT INTO Top_Transaction_Details(Pincode,District,State,Year,Quater,District_count,District_amount) VALUES(%s,%s,%s,%s,%s,%s,%s)',(row['Pincode'],row['District'],row['State'],row ['Year'],row['Quater'],row['District_count'],row['District_amount']))
    #Top_Tran_Det.to_sql(name="Top_Transaction_Details",con=engine,index=False,if_exists='append')

    Top_User_Det=top_user_details()
    stateformat(Top_User_Det['State'])
    stateformat(Top_User_Det['District'])
    for index, row in Top_User_Det.iterrows():
        mycursor.execute('INSERT INTO Top_User_Details(Pincode,District,State,Year,Quater,Registered_Users) VALUES(%s,%s,%s,%s,%s,%s)',(row['Pincode'],row['District'],row['State'],row ['Year'],row['Quater'],row['Registered_Users']))
    #Top_User_Det.to_sql(name="Top_User_Details",con=engine,index=False,if_exists='append')

In [32]:
load_data()

<mysql.connector.connection_cext.CMySQLConnection object at 0x0000027DCD551400>

C:\Users\Akshaya\AppData\Local\Temp\ipykernel_14632\2069009056.py:21: UserWarning: The provided table name 'Aggregate_Transaction_Details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Aggregate_Tran_Det.to_sql(name="Aggregate_Transaction_Details",con=engine,index=False,if_exists='append')
C:\Users\Akshaya\AppData\Local\Temp\ipykernel_14632\2069009056.py:25: UserWarning: The provided table name 'Aggregate_User_Details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Aggregate_User_Det.to_sql(name="Aggregate_User_Details",con=engine,index=False,if_exists='append')
C:\Users\Akshaya\AppData\Local\Temp\ipykernel_14632\2069009056.py:30: UserWarning: The provided table name 'Map_Transaction_Details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Map_Tran_Det.to_sql(name="Map_Transaction_Details",con=engine,index=False,if_exists='append')
C:\Users\Akshaya\AppData\Local\Temp\ipykernel_14632\2069009056.py:35: UserWarning: The provided table name 'Map_User_Details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Map_User_Det.to_sql(name="Map_User_Details",con=engine,index=False,if_exists='append')
C:\Users\Akshaya\AppData\Local\Temp\ipykernel_14632\2069009056.py:39: UserWarning: The provided table name 'Map_Total_Transaction_Details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Map_total_trans_Det.to_sql(name="Map_Total_Transaction_Details",con=engine,index=False,if_exists='append')
C:\Users\Akshaya\AppData\Local\Temp\ipykernel_14632\2069009056.py:43: UserWarning: The provided table name 'Map_Total_User_Details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Map_total_user_Det.to_sql(name="Map_Total_User_Details",con=engine,index=False,if_exists='append')
C:\Users\Akshaya\AppData\Local\Temp\ipykernel_14632\2069009056.py:48: UserWarning: The provided table name 'Top_Transaction_Details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Top_Tran_Det.to_sql(name="Top_Transaction_Details",con=engine,index=False,if_exists='append')
C:\Users\Akshaya\AppData\Local\Temp\ipykernel_14632\2069009056.py:53: UserWarning: The provided table name 'Top_User_Details' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Top_User_Det.to_sql(name="Top_User_Details",con=engine,index=False,if_exists='append')

In [18]:
# #connection to sql
# connection = mysql.connector.connect(
#     host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
#     port = 4000,
#     user = "3Pq3bYuANQHnv9P.root",
#     password = "M2U9mJayT54djDpU",
#     database = "test",
  
#     )
# print(connection)
# mycursor = connection.cursor(buffered=True)
# mycursor.execute("use project2")

In [3]:
import mysql.connector




mydb = mysql.connector.connect(
 host="localhost",
 user="root",
 password="new_password",


)


print(mydb)
mycursor = mydb.cursor(buffered=True)
engine=create_engine('mysql+mysqlconnector://root:new_password@localhost:3306/project2')

<mysql.connector.connection_cext.CMySQLConnection object at 0x0000021C390998B0>